spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:https://github.com/SpringWorkshop/speedy-cat-config.git}
server:
  port: 8781
eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_CLUSTER:http://localhost:8760}
management:
    security:
      enabled: false
info:
    version: @project.version@