version: '2'

services:
  service-monitor:
    container_name: service-monitor
    build:
      context: ../../service-monitor
      dockerfile: ./buildtask/Dockerfile
    working_dir: /app
    external_links:
      - registry-service-master
      - registry-service-replicate
    environment:
      APP_ENV: dev
      CONFIG_VERSION: master
      REGISTRY_CLUSTER: http://registry-service-master:8760/eureka/,http://registry-service-replicate:8760/eureka/
    expose:
      - 8771
    ports:
      - 8771:8771